export const countriesSouthAmerica = new Set([
  'brazil',
  'colombia',
  'argentina',
  'peru',
  'venezuela',
  'chile',
  'ecuador',
  'bolivia',
  'paraguay',
  'uruguay',
  'guyana',
  'suriname',
  'french guiana',
  'falkland islands',
]);

export const countriesAfrica = new Set([
  'nigeria',
  'ethiopia',
  'egypt',
  'dr congo',
  'tanzania',
  'south africa',
  'kenya',
  'uganda',
  'sudan',
  'algeria',
  'morocco',
  'angola',
  'ghana',
  'mozambique',
  'madagascar',
  `côte d'ivoire`,
  'cameroon',
  'niger',
  'mali',
  'burkina faso',
  'malawi',
  'zambia',
  'chad',
  'somalia',
  'senegal',
  'zimbabwe',
  'guinea',
  'rwanda',
  'benin',
  'burundi',
  'tunisia',
  'south sudan',
  'togo',
  'sierra leone',
  'libya',
  'congo',
  'central african republic',
  'liberia',
  'mauritania',
  'eritrea',
  'gambia',
  'botswana',
  'namibia',
  'gabon',
  'lesotho',
  'guinea-bissau',
  'equatorial guinea',
  'mauritius',
  'eswatini',
  'djibouti',
  'comoros',
  'cabo verde',
  'sao tome and principe',
  'seychelles',
]);

export const countriesOceania = new Set([
  'australia',
  'papua new guinea',
  'new zealand',
  'fiji',
  'solomon islands',
  'micronesia',
  'vanuatu',
  'samoa',
  'kiribati',
  'tonga',
  'marshall islands',
  'palau',
  'nauru',
  'tuvalu',
]);

export const countriesAsia = new Set([
  'india',
  'china',
  'indonesia',
  'pakistan',
  'bangladesh',
  'japan',
  'philippines',
  'vietnam',
  'iran',
  'turkey',
  'thailand',
  'myanmar',
  'south korea',
  'iraq',
  'afghanistan',
  'saudi arabia',
  'uzbekistan',
  'yemen',
  'malaysia',
  'nepal',
  'north korea',
  'syria',
  'sri lanka',
  'kazakhstan',
  'cambodia',
  'jordan',
  'azerbaijan',
  'tajikistan',
  'united arab emirates',
  'israel',
  'laos',
  'kyrgyzstan',
  'turkmenistan',
  'singapore',
  'state of palestine',
  'lebanon',
  'oman',
  'kuwait',
  'georgia',
  'mongolia',
  'armenia',
  'qatar',
  'bahrain',
  'timor-leste',
  'cyprus',
  'bhutan',
  'maldives',
  'brunei',
]);

export const countriesEurope = new Set([
  'russia',
  'germany',
  'france',
  'italy',
  'spain',
  'poland',
  'ukraine',
  'romania',
  'netherlands',
  'belgium',
  'sweden',
  'czech republic',
  'greece',
  'portugal',
  'hungary',
  'belarus',
  'austria',
  'switzerland',
  'serbia',
  'bulgaria',
  'denmark',
  'slovakia (slovak republic)',
  'finland',
  'norway',
  'ireland',
  'croatia',
  'moldova',
  'bosnia and herzegovina',
  'albania',
  'lithuania',
  'slovenia',
  'north macedonia',
  'latvia',
  'estonia',
  'luxembourg',
  'montenegro',
  'malta',
  'iceland',
  'andorra',
  'liechtenstein',
  'monaco',
  'san marino',
]);
